- project:
    check: &check-jobs
      jobs:
        - mcom03-linux66-buildroot-build
        - mcom03-qt-buildroot-build:
            files:
              - .*qt5
              - .*-sip
    gate: *check-jobs
